### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by kmickeletto** [larizzo/docker-insteon-mqtt#1]
Really excited about the possibility of this package.  Was getting errors trying to run this image, so I downloaded Dockerfile and entrypoint.sh and built a new image.  When trying to start, I am getting standard_init_linux.go:178: exec user process caused "exec format error".

Any suggestions?

Thanks much!

**Comment by larizzo** [comment]
I'll take a look, I haven't updated it in a really long time so it's probably broke with some more recent releases of insteon-mqtt. Should see an update in the next few days.

**Comment by larizzo** [comment]
I just pushed and update, should fix your issues. You can use my docker image if you want also instead of building it. https://hub.docker.com/r/larizzo/insteon-mqtt/

**Comment by kskenyon** [comment]
I'm getting the same error now.  Was there a regression?

**Comment by larizzo** [comment]
I'm not sure why you are getting that, one change I made was that I moved the install of insteon-mqtt to entrypoint.sh so it will install the latsest build every time you restart the container and you could also choose a different version by modifying the entrypoint.sh. I rebuild the image jsut now and pushed it up if you want to try this one.
