### ISSUE TITLE
Will not start after watchtower updated image

### ISSUE THREAD

**Issue by DCandE** [larizzo/docker-insteon-mqtt#2]
Watchtower updated the image now I get the error

```
OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"./entrypoint.sh\": stat ./entrypoint.sh: no such file or directory": unknown
```

**Comment by kskenyon** [comment]
Attaching to insteon-mqtt
insteon-mqtt  | standard_init_linux.go:228: exec user process caused: exec format error
insteon-mqtt exited with code 0
insteon-mqtt exited with code 1

I'm getting this error again.  Was there a regression somewhere?
