### ISSUE TITLE
insteon-mqtt | standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by kskenyon** [larizzo/docker-insteon-mqtt#6]
Attaching to insteon-mqtt
insteon-mqtt | standard_init_linux.go:228: exec user process caused: exec format error
insteon-mqtt exited with code 0
insteon-mqtt exited with code 1

I'm getting this error again. Was there a regression somewhere?

**Comment by larizzo** [comment]
I'm not sure why it's not working for you but the major change I made was installing insteon-mqtt one start up. I've reverted this change and added some more information for inital startup if you don't have a config file. If it's still not working can you please post the entire output of docker logs insteon-mqtt (replace with your container name).

**Comment by kskenyon** [comment]
The docker log only contains that one error line.

Could it be that I am running on Raspian64 on that machine?  I did finally see an error that it was pulling amd64 instead of aarch64.  It’s on a pi4.  

docker run -d --name=insteon-mqtt --net=bridge -v /home/pi/insteon-mqtt:/config:rw --device=/dev/ttyUSB0 larizzo/insteon-mqtt
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Also, I'm not running homeassistant.  I see that amd64 is specified on that line.  I want to use insteon-mqtt standalone.

Kevin

**Comment by larizzo** [comment]
I'm building my image only for amd64, I just tried a test to see if I can built multiarch images. Try using this image: `larizzo/insteon-mqtt:test ` if that works I'll push it to the latest tag.

**Comment by kskenyon** [comment]
This seems to be working now. Thanks. 

Kevin

Fatfingered from my iPhone

**Comment by larizzo** [comment]
I pushed the multiarch to the latest tag and deleted the test tag.
